In [28]:
import random
import numpy as np

# Function to create the random binary string 
def rand_key(p): 
	
	# Variable to store the string 
	key1 = []

	# Loop to find the string of desired length 
	for i in range(p): 
		
		# randint function to generate 
		# 0, 1 randomly and converting the result into str 
		temp = str(random.randint(0,1)) 

		# Concatenation the random 0, 1 to the final result 
		key1 += temp 
		
	return(key1)

# Driver Code 
n = 8
str1 = rand_key(n) 
print("Desired length random binary string is: ", str1) 

Desired length random binary string is:  ['0', '0', '0', '0', '0', '1', '0', '0']


In [29]:
#state of particles

down = np.array([[0], [1]])
up = np.array([[1], [0]])

In [30]:
#change up state in v+, v-
np.where((up==0) | (up==1), up^1, up)

array([[0],
       [1]])

In [31]:
#change up state in u+, u- && down state in u-
def convert(lst):
    return [-i for i in lst]

In [32]:
#change down state in v-
x = np.where((down==0) | (down==1), down^1, down)

array([[1],
       [0]])

In [27]:
#change down state in v+
x = np.where((down==0) | (down==1), down^1, down)
def convert(lst):
    return [-i for i in lst]

In [36]:
#change down state in u+
from copy import deepcopy
a = deepcopy(down)

[[0]
 [1]]
