In [12]:
import random
import numpy as np

# Function to create the random binary string 
def rand_key(p): 
	
	# Variable to store the string 
	key1 = []

	# Loop to find the string of desired length 
	for i in range(p): 
		
		# randint function to generate 
		# 0, 1 randomly and converting the result into str 
		temp = str(random.randint(0,1)) 

		# Concatenation the random 0, 1 to the final result 
		key1 += temp 
		
	return(key1)

# Driver Code 
n = 8
str1 = rand_key(n) 
print("Desired length random binary string is: ", str1) 

Desired length random binary string is:  ['0', '0', '1', '1', '1', '1', '1', '1']


In [13]:
#state of particles

down = np.array([[0], [1]])
up = np.array([[1], [0]])

In [14]:
#def insert_bob(state):
#    if (state == down).all:
#        v_plus = (0, 1)
#        v_minus = (0, 1)
#        u_plus = (-1, 0)
#        u_minus = (-1, 0)
#    if (state == up).all:
#        v_plus = (-1, 0)
#        u_plus = (0, 1)
#        v_minus = (1, 0)
#        u_minus = (0, -1)

#    print('v_plus ' 'v_minus ' 'u_plus ' 'u_minus')
#    print(v_plus, v_minus, u_plus, u_minus)

In [15]:
class bob_value:
    zero_one = np.array([[0], [1]])
    minus1_zero = np.array([[-1], [0]])
    one_zero = np.array([[1], [0]])
    zero_minus1 = np.array([[0], [-1]])

In [16]:
import numpy as np
array1 = np.array([[11, 22, 33, 44, 55],
             [66,  77,  88,  99, 100]])
print("Original arrays:")
print(array1)
i = [1,3,0,4,2]
result = array1[:,i]
print("New array:")
print(result)

Original arrays:
[[ 11  22  33  44  55]
 [ 66  77  88  99 100]]
New array:
[[ 22  44  11  55  33]
 [ 77  99  66 100  88]]


In [19]:
#change up state in v+ and v-
np.where((up==0) | (up==1), up^1, up)

array([[0],
       [1]])

In [21]:
#change up state in u+ and u-
def convert(lst):
    return [-i for i in lst]

In [22]:
#change down state in v-
np.where((down==0) | (down==1), down^1, down)

array([[1],
       [0]])